### PR TITLE
Morememberconfig

### PR DESCRIPTION
**Pull request by rajivnathan**
## Description
Adds the remaining memberoperatorconfig fields required for the migration of the rest of the member operator configuration.

## Checks
1. Have you run `make generate` target? **yes**

2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **yes** 

3. In case other projects are changed, please provides PR links.
    - host-operator: https://github.com/codeready-toolchain/host-operator/pull/474
    - member-operator: https://github.com/codeready-toolchain/member-operator/pull/269

### CODE REVIEW

**Review by alexeykazakov — COMMENTED** [review]
Looks like you missing a lot of `// +optional` :)

**Comment by rajivnathan** [comment]
Oops, added the missing `// +optional` in https://github.com/codeready-toolchain/api/pull/246/commits/307e190d8b32423f1aafd562d202b0f9242f4b7e

**Review by alexeykazakov — APPROVED** [review]
Looks good but you forgot to re-generate the files.

**Comment by rajivnathan** [comment]
Regenerated in https://github.com/codeready-toolchain/api/pull/246/commits/fe0da003e83a00254d14efc72f0e898b9ee8fdb4

**Pull request merged**
