### PR TITLE
Remove the deprecated CapacityThresholds from the ToolchainConfig

### PR DESCRIPTION
**Pull request by metlos**
## Description
This removes the deprecated CapacityThreshold fields from the ToolchainConfig. This configuration is now achieved using the dedicated `SpaceProvisionerConfig` CRD and so keeping it in the ToolchainConfig would only be confusing.

See https://issues.redhat.com/browse/KUBESAW-36.

## Checks
1. Did you run `make generate` target? **yes**

2. Did `make generate` change anything in other projects (host-operator, member-operator)? **yes**

3. In case of **new** CRD, did you the following? **N/A**
    - make/generate.mk in this repository
    - `resources/setup/roles/host.yaml` in the sandbox-sre repository
    - `PROJECT` file: https://github.com/codeready-toolchain/host-operator/blob/master/PROJECT
    - `CSV` file: https://github.com/codeready-toolchain/host-operator/blob/master/config/manifests/bases/host-operator.clusterserviceversion.yaml

4. In case other projects are changed, please provides PR links.
    - toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/379
    - host-operator: https://github.com/codeready-toolchain/host-operator/pull/1000
    - toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/935

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]
Let's make sure we deleted these fields from sandbox-sre and infra-deployment before merging this PR

**Comment by alexeykazakov** [comment]
Also, I don't see any PR with re-generated CRDs.

**Review by mfrancisc — APPROVED** [review]

**Comment by mfrancisc** [comment]
As per infra-deployments you can find the toolchainconfig definitions in here: https://github.com/redhat-appstudio/infra-deployments/tree/main/components/sandbox/toolchain-host-operator . There's multiple of those for different environements

**Review by MatousJobanek — APPROVED** [review]

**Comment by MatousJobanek** [comment]
Alexey is right, the host-operator PR doesn't have updated ToolchainConfig CRD

**Comment by metlos** [comment]
> Alexey is right, the host-operator PR doesn't contain the updated ToolchainConfig CRD

huh, thanks for pointing it out. I'm sure I ran `make generate` here but somehow I lost the changes in host operator. https://github.com/codeready-toolchain/host-operator/pull/1000 should now be updated with the changes to the CRD.

**Review by rajivnathan — APPROVED** [review]

**Pull request merged**
