### PR TITLE
add kubesaw-authenticated username constant

### PR DESCRIPTION
**Pull request by filariow**
Signed-off-by: Francesco Ilario <filario@redhat.com>

JIRA: https://issues.redhat.com/browse/ASC-531

## Description
This PR adds a constant value for the `kubesaw-authenticated` special user.

## Checks
1. Did you run `make generate` target? **yes**

2. Did `make generate` change anything in other projects (host-operator, member-operator)? **no**

3. In case of **new** CRD, did you the following? N/A

4. In case other projects are changed, please provides PR links. N/A

### CODE REVIEW

**Review by mfrancisc — COMMENTED** [review]
minor - but maybe we could add a description explaining where is this used , or a TODO explaining where / how it will be used ? 

Just to make it clear for others that might find this as unused. WDYT?

**Comment by filariow** [comment]
> minor - but maybe we could add a description explaining where is this used , or a TODO explaining where / how it will be used ?
> 
> Just to make it clear for others that might find this as unused. WDYT?

makes sense. Let me add some comments.

**Comment by filariow** [comment]
@mfrancisc done in 37dd1b47731adeb6948d75f7d94c02a691be6eeb

**Review by mfrancisc — APPROVED** [review]
Looks good 👍 
Thanks for addressing my comment!

**Review by alexeykazakov — APPROVED** [review]

**Review by fbm3307 — APPROVED** [review]
LGTM

**Pull request merged**
