### PR TITLE
remove webConsolePlugin from ToolchainClusterConfig (phase 2)

### PR DESCRIPTION
**Pull request by xcoulon**
Pendo has been decommisioned, we don't need this plugin anymore

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]
Looks good. But let's make sure we update stage and prod configuration first to make sure those fields are not present in actual ToolchainConfig resources anymore before merging this PR.

**Comment by alexeykazakov** [comment]
And also please make sure there are host and member CRDs changes without any go.mod replace in them (and they are green) before merging this PR.

**Comment by xcoulon** [comment]
> Looks good. But let's make sure we update stage and prod configuration first to make sure those fields are not present in actual ToolchainConfig resources anymore before merging this PR.

already done in https://github.com/codeready-toolchain/sandbox-sre/pull/1885 :)

**Comment by xcoulon** [comment]
> And also please make sure there are host and member CRDs changes without any go.mod replace in them (and they are green) before merging this PR.

I'm a bit confused by your request, could you elaborate on what needs to be verified exactly? 
Are you suggesting that we should have a set of PRs which only contain the removal in the CRDs, without any change in the Go types?

**Comment by xcoulon** [comment]
> > And also please make sure there are host and member CRDs changes without any go.mod replace in them (and they are green) before merging this PR.
> 
> I'm a bit confused by your request, could you elaborate on what needs to be verified exactly? Are you suggesting that we should have a set of PRs which only contain the removal in the CRDs, without any change in the Go types?

never mind, I found the explanations in https://github.com/codeready-toolchain/host-operator/pull/1068#discussion_r1693303743


so here are the changes you requested (hopefully):
https://github.com/codeready-toolchain/host-operator/pull/1069
https://github.com/codeready-toolchain/member-operator/pull/589
https://github.com/codeready-toolchain/toolchain-e2e/pull/1021

**Review by mfrancisc — APPROVED** [review]

**Review by rajivnathan — APPROVED** [review]

**Pull request merged**
