### PR TITLE
refactor: new 'MasterUserRecord.Spec.TierName' field

### PR DESCRIPTION
**Pull request by xcoulon**
Fixes https://issues.redhat.com/browse/CRT-1321

See also:
https://github.com/codeready-toolchain/host-operator/pull/539
https://github.com/codeready-toolchain/toolchain-e2e/pull/411
https://github.com/codeready-toolchain/member-operator/pull/310
https://github.com/codeready-toolchain/registration-service/pull/227

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Review by MatousJobanek — COMMENTED** [review]
Looks good, just missing the PR for host-operator repo.
And it would be nice to update the dependency to api in reg-service as well - just for sure :-).

**Comment by xcoulon** [comment]
> Looks good, just missing the PR for host-operator repo. And it would be nice to update the dependency to api in reg-service as well - just for sure :-).

yes, other PRs should be coming soon (tm). I just wanted to push the changes here first, but I don't intend to merge this one until everything is ready (ie, tested and approved) ;)

**Comment by xcoulon** [comment]
> codeready-toolchain/registration-service#227

I forgot to comment that there's a PR for registration service as well: https://github.com/codeready-toolchain/registration-service/pull/227

**Comment by MatousJobanek** [comment]
@xcoulon could you please update also the `printcolumn` annotation?
```
// +kubebuilder:printcolumn:name="Tier",type="string",JSONPath=`.spec.userAccounts[].spec.nsTemplateSet.tierName`
```
so it uses the new field?

**Comment by xcoulon** [comment]
> ```
> // +kubebuilder:printcolumn:name="Tier",type="string",JSONPath=`.spec.userAccounts[].spec.nsTemplateSet.tierName`
> ```

done in https://github.com/codeready-toolchain/api/pull/266/commits/72e8d12f0de1b0c7abdf502253cb16194231c2d1

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
