### PR TITLE
feat(CRT-227): add script & target that generates CSV for host-operator

### PR DESCRIPTION
**Pull request by MatousJobanek**
## Description
Adds a script that generates:
* CSV from previous version - for now it uses `0.0.0` as some kind of template for the beginning (the operator-sdk has some issues so this is a workaround for it)
* as part of the `operator-sdk olm-catalog gen-csv .....` command it copies also CRDs to the dir of the CSV version
* creates `deploy_csv.yaml` file containing resources `CatalogSource` & `ConfigMap` that help with adding the operator to operator catalog
* creates `install_operator.yaml` file containing resources `OperatorGroup` & `Subscription` that help with installing the operator into a namespace

For now, it is executed only for host-operator. PR for member-operator will come afterwards

## Checks
1. Have you run `make generate` target? **[yes/no]**
**yes**

2. Does `make generate` change anything in other projects (host-operator, member-operator)? **[yes/no]**
**yes**

3. In case other projects are changed, please provides PR links.
    - host-operator: https://github.com/codeready-toolchain/host-operator/pull/73

### CODE REVIEW

**Comment by alexeykazakov** [comment]
There seems to be a cycle dependency between this PR and the host PRs:
```
...
INFO[0000] Created deploy/olm-catalog/host-operator/0.0.1/host-operator.v0.0.1.clusterserviceversion.yaml 
INFO[0000] Created deploy/olm-catalog/host-operator/host-operator.package.yaml 
./scripts/olm-catalog.sh: line 114: ../host-operator/hack/deploy_csv.yaml: No such file or directory
./scripts/olm-catalog.sh: line 139: ../host-operator/hack/install_operator.yaml: No such file or directory
make: *** [make/generate.mk:44: generate-csv] Error 1
```

By cycle dependency I mean that this PR was used to create https://github.com/codeready-toolchain/host-operator/pull/73 but https://github.com/codeready-toolchain/host-operator/pull/73 meanwhile is required to be merged before `make generate` can work in this PR.

Which is not critical but we should merge https://github.com/codeready-toolchain/host-operator/pull/73 before we can merge this PR.

**Comment by alexeykazakov** [comment]
Also, `make generate` always updates SCVs (in host):
```
modified:   deploy/olm-catalog/host-operator/0.0.1/host-operator.v0.0.1.clusterserviceversion.yaml
modified:   hack/deploy_csv.yaml
```
It generates new `alm-examples` annotations. I guess it's because it uses maps to marshal it to yaml, so, order is different every time.

It's probably not a big deal but something worth keeping in mind.

**Comment by MatousJobanek** [comment]
Thanks for your review @alexeykazakov 

> There seems to be a cycle dependency between this PR and the host PRs:

yes, you are right, sorry for not being clear in the description. The error that you pasted is acutally an insuficciency of the script logic - let me fix it: 1899004
Anyway, the generation relies on other files such as `csv-config.yaml/olm-catalog` and `olm-catalog/host-operator/0.0.0/host-operator.v0.0.0.clusterserviceversion.yaml` If you want I can split the PR in host-operator repo. 

> Which is not critical but we should merge codeready-toolchain/host-operator#73 before we can merge this PR.

it doesn't matter which PR is merged first - there is no additional check or jobs when the PRs are merged. We just need to be sure that we merged both, but no matter in which order.

> Also, make generate always updates SCVs (in host):...
 It generates new alm-examples annotations. I guess it's because it uses maps to marshal it to yaml, so, order is different every time.

Not every time, but very often. But I know about it, however, there is no way we could avoid it. Let me add a comment to the PR template to make it clear: 0496732

**Comment by alexeykazakov** [comment]
No need to split up the host PR. It’s fine.

**Pull request merged**
