### PR TITLE
add disableInheritance for Spaces and SpaceRequests

### PR DESCRIPTION
**Pull request by mmulholla**
## Description
Add disableInheritance flag to Space and SpaceRequest
see: https://issues.redhat.com/browse/ASC-428

## Checks
1. Did you run `make generate` target? **yes/no**

2. Did `make generate` change anything in other projects (host-operator, member-operator)? **yes**

3. In case of **new** CRD, did you the following? **no**
    - make/generate.mk in this repository
    - `resources/setup/roles/host.yaml` in the sandbox-sre repository
    - `PROJECT` file: https://github.com/codeready-toolchain/host-operator/blob/master/PROJECT
    - `CSV` file: https://github.com/codeready-toolchain/host-operator/blob/master/config/manifests/bases/host-operator.clusterserviceversion.yaml

4. In case other projects are changed, please provides PR links.
    - host-operator: https://github.com/codeready-toolchain/host-operator/pull/927
    - member-operator: https://github.com/codeready-toolchain/member-operator/pull/500

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Review by alexeykazakov — APPROVED** [review]
The PR looks good but please create separate PR for the host operator repo just to update the CRD.
This is how we usually introduce API changes:
- Change the API and generate the CRDs in the corresponding operator repos locally.
- Create an API PR and PRs for the corresponding operators repos with the updated CRDs.
- Get all of those PRs merged.
- Now you can create PRs which actually use the new API.
See an example of the first step here: https://github.com/codeready-toolchain/api/pull/385

**Comment by mmulholla** [comment]
PR https://github.com/codeready-toolchain/host-operator/pull/927 created with just results from make generate.

**Comment by mmulholla** [comment]
also one for member-operator: https://github.com/codeready-toolchain/member-operator/pull/500

**Review by alexeykazakov — COMMENTED** [review]
Are you sure there is no changes in `api/v1alpha1/zz_generated.deepcopy.go` when you do `make generate`?

**Review by rajivnathan — APPROVED** [review]

**Review by mfrancisc — COMMENTED** [review]
Looks good 👍 

As Alexey mentioned you should have changes to `api/v1alpha1/zz_generated.openapi.go` , I just double checked locally.

**Comment by mmulholla** [comment]
I have added the file. Thx for the heads-up.

**Comment by mmulholla** [comment]
> Are you sure there is no changes in `api/v1alpha1/zz_generated.deepcopy.go` when you do `make generate`?

Sure

**Pull request merged**
