### PR TITLE
add public-viewer config

### PR DESCRIPTION
**Pull request by filariow**
Signed-off-by: Francesco Ilario <filario@redhat.com>

## Description
This PR adds the `PublicViewerConfig` optional field to the `ToolchainConfig` CRD

## Checks
1. Did you run `make generate` target? **yes**

2. Did `make generate` change anything in other projects (host-operator, member-operator)? **yes**

3. In case of **new** CRD, did you the following? N/A
    - make/generate.mk in this repository
    - `resources/setup/roles/host.yaml` in the sandbox-sre repository
    - `PROJECT` file: https://github.com/codeready-toolchain/host-operator/blob/master/PROJECT
    - `CSV` file: https://github.com/codeready-toolchain/host-operator/blob/master/config/manifests/bases/host-operator.clusterserviceversion.yaml

4. In case other projects are changed, please provides PR links.
    - host-operator: https://github.com/codeready-toolchain/host-operator/pull/1021
    - member-operator: N/A

### CODE REVIEW

**Review by mfrancisc — COMMENTED** [review]
It seems that the changes in `zz_generated.openapi.go` are missing , or am I wrong ? 🤔

**Review by mfrancisc — APPROVED** [review]
LGTM

**Review by alexeykazakov — APPROVED** [review]

**Review by fbm3307 — APPROVED** [review]
LGTM

**Review by MatousJobanek — APPROVED** [review]

**Comment by filariow** [comment]
superseded by #430

**Pull request closed without merging**
